# Site settings
title: "SingaporeLUG"
bye_message: "Thanks!"
baseurl: "/"
url: "https://singaporelug.org"
disqus: gjuniioor

# Header settings
nick: "SingaporeLUG"
mail:
    domain: "usa"
    ext: ".com"
source_code:
    server: "github.com"
    nick: "singaporelug"
blog:
    server: "wordpress.com"
    nick: "singaporelug"
fingerprint_key: "5E12 9ABC C2A9 564B C048  2DF9 D327 0D10 BC71 CF75"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
